// <auto-generated />
using System;
using HashKeyChain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HashKeyChain.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hashkeychain")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HashKeyChain.Data.TradeRequestRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TradeReference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("UiCulture")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.ToTable("TradeRequests", "hashkeychain");
                });

            modelBuilder.Entity("HashKeyChain.Domain.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PreferredCulture")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Users", "hashkeychain");
                });

            modelBuilder.Entity("HashKeyChain.Domain.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("AfterStatus")
                        .HasColumnType("int");

                    b.Property<int?>("BeforeStatus")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TradeId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionHash")
                        .HasMaxLength(66)
                        .HasColumnType("nvarchar(66)");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("TradeId");

                    b.ToTable("AuditEntries", "hashkeychain");
                });

            modelBuilder.Entity("HashKeyChain.Domain.ChainTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long?>("BlockNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("ChainId")
                        .HasColumnType("int");

                    b.Property<string>("ContractAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ExplorerUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("FromAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("GasUsed")
                        .HasColumnType("bigint");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("TradeId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionHash")
                        .HasMaxLength(66)
                        .HasColumnType("nvarchar(66)");

                    b.HasKey("Id");

                    b.HasIndex("TradeId");

                    b.ToTable("ChainTransactions", "hashkeychain");
                });

            modelBuilder.Entity("HashKeyChain.Domain.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("WalletAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Companies", "hashkeychain");
                });

            modelBuilder.Entity("HashKeyChain.Domain.DocumentCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualValue")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Detail")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ExpectedValue")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsSoft")
                        .HasColumnType("bit");

                    b.Property<bool>("Passed")
                        .HasColumnType("bit");

                    b.Property<string>("RuleKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("VerificationRunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VerificationRunId");

                    b.ToTable("DocumentChecks", "hashkeychain");
                });

            modelBuilder.Entity("HashKeyChain.Domain.DocumentVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisStatus")
                        .HasColumnType("int");

                    b.Property<double?>("Confidence")
                        .HasColumnType("float");

                    b.Property<int?>("DetectedType")
                        .HasColumnType("int");

                    b.Property<string>("ExtractedFieldsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceLanguage")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("TradeDocumentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Sha256");

                    b.HasIndex("TradeDocumentId");

                    b.ToTable("DocumentVersions", "hashkeychain");
                });

            modelBuilder.Entity("HashKeyChain.Domain.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BuyerApproverUserId")
                        .HasColumnType("int");

                    b.Property<int>("BuyerCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("BuyerWalletAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("ConditionsLocked")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime?>("DocumentSubmissionDeadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpectedProductDescription")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<decimal?>("ExpectedQuantity")
                        .HasColumnType("decimal(38,18)");

                    b.Property<bool>("IsFunded")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRefunded")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSettled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LatestShipmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LatestVerdict")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("decimal(38,18)");

                    b.Property<DateTime?>("PaymentExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentToken")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PurchaseOrderNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RefundTxHash")
                        .HasMaxLength(66)
                        .HasColumnType("nvarchar(66)");

                    b.Property<int>("SellerCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("SellerWalletAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SettlementTxHash")
                        .HasMaxLength(66)
                        .HasColumnType("nvarchar(66)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TradeReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("TransportMode")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VerifierUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuyerApproverUserId");

                    b.HasIndex("BuyerCompanyId");

                    b.HasIndex("SellerCompanyId");

                    b.HasIndex("TradeReference")
                        .IsUnique();

                    b.HasIndex("VerifierUserId");

                    b.ToTable("Trades", "hashkeychain");
                });

            modelBuilder.Entity("HashKeyChain.Domain.TradeDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("TradeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TradeId", "DocumentType")
                        .IsUnique();

                    b.ToTable("TradeDocuments", "hashkeychain");
                });

            modelBuilder.Entity("HashKeyChain.Domain.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles", "hashkeychain");
                });

            modelBuilder.Entity("HashKeyChain.Domain.VerificationRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiRiskLevel")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<DateTime>("RunAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("TradeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TradeId");

                    b.ToTable("VerificationRuns", "hashkeychain");
                });

            modelBuilder.Entity("HashKeyChain.Domain.AppUser", b =>
                {
                    b.HasOne("HashKeyChain.Domain.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HashKeyChain.Domain.AuditEntry", b =>
                {
                    b.HasOne("HashKeyChain.Domain.Trade", "Trade")
                        .WithMany("AuditEntries")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("HashKeyChain.Domain.ChainTransaction", b =>
                {
                    b.HasOne("HashKeyChain.Domain.Trade", "Trade")
                        .WithMany("ChainTransactions")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("HashKeyChain.Domain.DocumentCheck", b =>
                {
                    b.HasOne("HashKeyChain.Domain.VerificationRun", "VerificationRun")
                        .WithMany("Checks")
                        .HasForeignKey("VerificationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VerificationRun");
                });

            modelBuilder.Entity("HashKeyChain.Domain.DocumentVersion", b =>
                {
                    b.HasOne("HashKeyChain.Domain.TradeDocument", "TradeDocument")
                        .WithMany("Versions")
                        .HasForeignKey("TradeDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeDocument");
                });

            modelBuilder.Entity("HashKeyChain.Domain.Trade", b =>
                {
                    b.HasOne("HashKeyChain.Domain.AppUser", "BuyerApproverUser")
                        .WithMany()
                        .HasForeignKey("BuyerApproverUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HashKeyChain.Domain.Company", "BuyerCompany")
                        .WithMany()
                        .HasForeignKey("BuyerCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HashKeyChain.Domain.Company", "SellerCompany")
                        .WithMany()
                        .HasForeignKey("SellerCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HashKeyChain.Domain.AppUser", "VerifierUser")
                        .WithMany()
                        .HasForeignKey("VerifierUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BuyerApproverUser");

                    b.Navigation("BuyerCompany");

                    b.Navigation("SellerCompany");

                    b.Navigation("VerifierUser");
                });

            modelBuilder.Entity("HashKeyChain.Domain.TradeDocument", b =>
                {
                    b.HasOne("HashKeyChain.Domain.Trade", "Trade")
                        .WithMany("Documents")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("HashKeyChain.Domain.UserRole", b =>
                {
                    b.HasOne("HashKeyChain.Domain.AppUser", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HashKeyChain.Domain.VerificationRun", b =>
                {
                    b.HasOne("HashKeyChain.Domain.Trade", "Trade")
                        .WithMany("VerificationRuns")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("HashKeyChain.Domain.AppUser", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("HashKeyChain.Domain.Company", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HashKeyChain.Domain.Trade", b =>
                {
                    b.Navigation("AuditEntries");

                    b.Navigation("ChainTransactions");

                    b.Navigation("Documents");

                    b.Navigation("VerificationRuns");
                });

            modelBuilder.Entity("HashKeyChain.Domain.TradeDocument", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("HashKeyChain.Domain.VerificationRun", b =>
                {
                    b.Navigation("Checks");
                });
#pragma warning restore 612, 618
        }
    }
}
